[default]
duration = "10s"
mode = "center"
sorting = "random"
transition_time = 3000
path = "~/wallpapers/"

# Transition differently on each moniotor
[DP-1]
duration = "10s"

[DP-2]
duration = "11s"

[DP-3]
duration = "12s"